const POETRY_DATA_EXTRA2 = {
    'fernhill': {
        id: 'fernhill',
        title: 'Fern Hill',
        author: 'Dylan Thomas',
        lat: 51.81,
        lng: -4.36,
        locationName: 'Llangain, Carmarthenshire',
        locationCoords: '51.81° N, 4.36° W',
        type: 'Inscribed Location',
        typeTag: 'The Welsh Lyric',
        accuracy: 'confirmed',
        era: '20th Century',
        desc: 'A nostalgic and lyrical reflection on childhood innocence spent at his aunt\'s farm in Carmarthenshire, Wales.',
        image: 'https://picsum.photos/seed/fernhill/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Now as I was young and easy under the apple boughs</p><p class="font-body text-lg leading-[1.8]">About the lilting house and happy as the grass was green,</p><p class="font-body text-lg leading-[1.8]">The night above the dingle starry,</p><p class="font-body text-lg leading-[1.8]">Time let me hail and climb</p><p class="font-body text-lg leading-[1.8]">Golden in the heydays of his eyes.</p></div>`
    },
    'coole': {
        id: 'coole',
        title: 'The Wild Swans at Coole',
        author: 'W.B. Yeats',
        lat: 53.08,
        lng: -8.84,
        locationName: 'Coole Park, County Galway',
        locationCoords: '53.08° N, 8.84° W',
        type: 'Inscribed Location',
        typeTag: 'The Irish Lyric',
        accuracy: 'confirmed',
        era: '20th Century',
        desc: 'Written at Lady Gregory\'s estate, Yeats reflects on the passage of time and the enduring beauty of the swans upon the lake.',
        image: 'https://picsum.photos/seed/coole/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">The trees are in their autumn beauty,</p><p class="font-body text-lg leading-[1.8]">The woodland paths are dry,</p><p class="font-body text-lg leading-[1.8]">Under the October twilight the water</p><p class="font-body text-lg leading-[1.8]">Mirrors a still sky;</p><p class="font-body text-lg leading-[1.8]">Upon the brimming water among the stones</p><p class="font-body text-lg leading-[1.8]">Are nine-and-fifty swans.</p></div>`
    },
    'digging': {
        id: 'digging',
        title: 'Digging',
        author: 'Seamus Heaney',
        lat: 54.80,
        lng: -6.52,
        locationName: 'Bellaghy, County Londonderry',
        locationCoords: '54.80° N, 6.52° W',
        type: 'Inscribed Location',
        typeTag: 'The Irish Lyric',
        accuracy: 'approximate',
        era: '20th Century',
        desc: 'Heaney compares his pen to his father\'s and grandfather\'s spades, finding his own way to dig into the rich history of his homeland.',
        image: 'https://picsum.photos/seed/digging/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Between my finger and my thumb</p><p class="font-body text-lg leading-[1.8]">The squat pen rests; snug as a gun.</p></div><div class="space-y-4 max-w-xl pt-6"><p class="font-body text-lg leading-[1.8]">Under my window, a clean rasping sound</p><p class="font-body text-lg leading-[1.8]">When the spade sinks into gravelly ground:</p><p class="font-body text-lg leading-[1.8]">My father, digging.</p></div>`
    },
    'auldlang': {
        id: 'auldlang',
        title: 'Auld Lang Syne',
        author: 'Robert Burns',
        lat: 55.07,
        lng: -3.61,
        locationName: 'Dumfries, Scotland',
        locationCoords: '55.07° N, 3.61° W',
        type: 'Inscribed Location',
        typeTag: 'The Scottish Lyric',
        accuracy: 'compositional',
        era: '18th Century',
        desc: 'The iconic Scottish poem and song dedicated to preserving old friendships and looking back fondly on the past.',
        image: 'https://picsum.photos/seed/auldlang/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Should auld acquaintance be forgot,</p><p class="font-body text-lg leading-[1.8]">and never brought to mind?</p><p class="font-body text-lg leading-[1.8]">Should auld acquaintance be forgot,</p><p class="font-body text-lg leading-[1.8]">and auld lang syne?</p></div>`
    },
    'iam': {
        id: 'iam',
        title: 'I Am!',
        author: 'John Clare',
        lat: 52.62,
        lng: -0.32,
        locationName: 'Northamptonshire, England',
        locationCoords: '52.62° N, 0.32° W',
        type: 'Inscribed Location',
        typeTag: 'The Romantic Lyric',
        accuracy: 'compositional',
        era: '19th Century',
        desc: 'Written during his time in an asylum, Clare powerfully asserts his existence amidst profound isolation.',
        image: 'https://picsum.photos/seed/iam/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">I am—yet what I am none cares or knows;</p><p class="font-body text-lg leading-[1.8]">My friends forsake me like a memory lost:</p><p class="font-body text-lg leading-[1.8]">I am the self-consumer of my woes—</p><p class="font-body text-lg leading-[1.8]">They rise and vanish in oblivious host.</p></div>`
    },
    'cherry': {
        id: 'cherry',
        title: 'Loveliest of Trees, the Cherry Now',
        author: 'A.E. Housman',
        lat: 52.60,
        lng: -2.75,
        locationName: 'Shropshire, England',
        locationCoords: '52.60° N, 2.75° W',
        type: 'Inscribed Location',
        typeTag: 'The Pastoral Lyric',
        accuracy: 'approximate',
        era: '19th Century',
        desc: 'A poignant reflection on the fleeting nature of life and beauty, set amidst the blooming cherry trees of the English countryside.',
        image: 'https://picsum.photos/seed/cherry/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Loveliest of trees, the cherry now</p><p class="font-body text-lg leading-[1.8]">Is hung with bloom along the bough,</p><p class="font-body text-lg leading-[1.8]">And stands about the woodland ride</p><p class="font-body text-lg leading-[1.8]">Wearing white for Eastertide.</p></div>`
    },
    'grantchester': {
        id: 'grantchester',
        title: 'The Old Vicarage, Grantchester',
        author: 'Rupert Brooke',
        lat: 52.17,
        lng: 0.09,
        locationName: 'Grantchester, Cambridgeshire',
        locationCoords: '52.17° N, 0.09° E',
        type: 'Inscribed Location',
        typeTag: 'The Pastoral Lyric',
        accuracy: 'confirmed',
        era: '20th Century',
        desc: 'A nostalgic ode to an idealized English village, written from the perspective of an expatriate in Berlin.',
        image: 'https://picsum.photos/seed/grantchester/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Just now the lilac is in bloom,</p><p class="font-body text-lg leading-[1.8]">All before my little room;</p><p class="font-body text-lg leading-[1.8]">And in my flower-beds, I think,</p><p class="font-body text-lg leading-[1.8]">Smile the carnation and the pink.</p></div>`
    },
    'elegy': {
        id: 'elegy',
        title: 'Elegy Written in a Country Churchyard',
        author: 'Thomas Gray',
        lat: 51.52,
        lng: -0.58,
        locationName: 'Stoke Poges, Buckinghamshire',
        locationCoords: '51.52° N, 0.58° W',
        type: 'Inscribed Location',
        typeTag: 'The Pastoral Lyric',
        accuracy: 'confirmed',
        era: '18th Century',
        desc: 'A solemn mediation on mortality and the unrecognized potential of the common folk buried in a rural churchyard.',
        image: 'https://picsum.photos/seed/elegy/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">The curfew tolls the knell of parting day,</p><p class="font-body text-lg leading-[1.8]">The lowing herd wind slowly o'er the lea,</p><p class="font-body text-lg leading-[1.8]">The plowman homeward plods his weary way,</p><p class="font-body text-lg leading-[1.8]">And leaves the world to darkness and to me.</p></div>`
    },
    'binsey': {
        id: 'binsey',
        title: 'Binsey Poplars',
        author: 'Gerard Manley Hopkins',
        lat: 51.76,
        lng: -1.29,
        locationName: 'Binsey, Oxfordshire',
        locationCoords: '51.76° N, 1.29° W',
        type: 'Inscribed Location',
        typeTag: 'The Nature Lyric',
        accuracy: 'confirmed',
        era: '19th Century',
        desc: 'An impassioned ecological lament over the felling of a beloved row of poplar trees near Oxford.',
        image: 'https://picsum.photos/seed/binsey/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">My aspens dear, whose airy cages quelled,</p><p class="font-body text-lg leading-[1.8]">Quelled or quenched in leaves the leaping sun,</p><p class="font-body text-lg leading-[1.8]">All felled, felled, are all felled;</p><p class="font-body text-lg leading-[1.8]">Of a fresh and following folded rank</p><p class="font-body text-lg leading-[1.8]">Not spared, not one.</p></div>`
    },
    'littlegidding': {
        id: 'littlegidding',
        title: 'Little Gidding',
        author: 'T.S. Eliot',
        lat: 52.42,
        lng: -0.33,
        locationName: 'Little Gidding, Cambridgeshire',
        locationCoords: '52.42° N, 0.33° W',
        type: 'Inscribed Location',
        typeTag: 'The Modernist Lyric',
        accuracy: 'confirmed',
        era: '20th Century',
        desc: 'The culmination of Eliot\'s Four Quartets, exploring themes of fire, redemption, and the spiritual intensity of a midwinter journey to an English village.',
        image: 'https://picsum.photos/seed/littlegidding/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Midwinter spring is its own season</p><p class="font-body text-lg leading-[1.8]">Sempiternal though sodden towards sundown,</p><p class="font-body text-lg leading-[1.8]">Suspended in time, between pole and tropic.</p><p class="font-body text-lg leading-[1.8]">When the short day is brightest, with frost and fire.</p></div>`
    },
    'frost': {
        id: 'frost',
        title: 'Frost at Midnight',
        author: 'Samuel Taylor Coleridge',
        lat: 51.15,
        lng: -3.15,
        locationName: 'Nether Stowey, Somerset',
        locationCoords: '51.15° N, 3.15° W',
        type: 'Inscribed Location',
        typeTag: 'The Romantic Lyric',
        accuracy: 'confirmed',
        era: '18th Century',
        desc: 'Coleridge reflects by the fire on a quiet winter night upon his past in the city and his hopes that his infant son will grow up immersed in nature.',
        image: 'https://picsum.photos/seed/frost/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">The Frost performs its secret ministry,</p><p class="font-body text-lg leading-[1.8]">Unhelped by any wind. The owlet's cry</p><p class="font-body text-lg leading-[1.8]">Came loud—and hark, again! loud as before.</p></div>`
    },
    'jerusalem': {
        id: 'jerusalem',
        title: 'Jerusalem',
        author: 'William Blake',
        lat: 50.80,
        lng: -0.65,
        locationName: 'Felpham, West Sussex',
        locationCoords: '50.80° N, 0.65° W',
        type: 'Inscribed Location',
        typeTag: 'The Romantic Lyric',
        accuracy: 'compositional',
        era: '19th Century',
        desc: 'Based on the legend that a young Jesus visited England, this visionary poem calls for the building of a new Jerusalem in "England\'s green and pleasant land."',
        image: 'https://picsum.photos/seed/jerusalem/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">And did those feet in ancient time</p><p class="font-body text-lg leading-[1.8]">Walk upon England's mountains green?</p><p class="font-body text-lg leading-[1.8]">And was the holy Lamb of God</p><p class="font-body text-lg leading-[1.8]">On England's pleasant pastures seen?</p></div>`
    },
    'vagabond': {
        id: 'vagabond',
        title: 'The Vagabond',
        author: 'Robert Louis Stevenson',
        lat: 55.54,
        lng: -2.85,
        locationName: 'Scottish Borders',
        locationCoords: '55.54° N, 2.85° W',
        type: 'Inscribed Location',
        typeTag: 'The Scottish Lyric',
        accuracy: 'compositional',
        era: '19th Century',
        desc: 'A spirited celebration of the solitary, wandering life unburdened by material possessions.',
        image: 'https://picsum.photos/seed/vagabond/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Give to me the life I love,</p><p class="font-body text-lg leading-[1.8]">Let the lave go by me,</p><p class="font-body text-lg leading-[1.8]">Give the jolly heaven above</p><p class="font-body text-lg leading-[1.8]">And the byway nigh me.</p></div>`
    },
    'lifebronte': {
        id: 'lifebronte',
        title: 'Life',
        author: 'Charlotte Brontë',
        lat: 53.83,
        lng: -1.95,
        locationName: 'Haworth, West Yorkshire',
        locationCoords: '53.83° N, 1.95° W',
        type: 'Inscribed Location',
        typeTag: 'The Victorian Lyric',
        accuracy: 'compositional',
        era: '19th Century',
        desc: 'A hopeful reflection arguing that the gloomy parts of life are temporary and joy will inevitably follow.',
        image: 'https://picsum.photos/seed/lifebronte/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Life, believe, is not a dream</p><p class="font-body text-lg leading-[1.8]">So dark as sages say;</p><p class="font-body text-lg leading-[1.8]">Oft a little morning rain</p><p class="font-body text-lg leading-[1.8]">Foretells a pleasant day.</p></div>`
    },
    'listeners': {
        id: 'listeners',
        title: 'The Listeners',
        author: 'Walter de la Mare',
        lat: 51.25,
        lng: 0.50,
        locationName: 'Kent, England',
        locationCoords: '51.25° N, 0.50° E',
        type: 'Inscribed Location',
        typeTag: 'The Modernist Lyric',
        accuracy: 'compositional',
        era: '20th Century',
        desc: 'A mysterious and atmospheric poem about a Traveller who knocks at a lonely, moonlit house filled only with ghostly listeners.',
        image: 'https://picsum.photos/seed/listeners/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">'Is there anybody there?' said the Traveller,</p><p class="font-body text-lg leading-[1.8]">Knocking on the moonlit door;</p><p class="font-body text-lg leading-[1.8]">And his horse in the silence champed the grasses</p><p class="font-body text-lg leading-[1.8]">Of the forest's ferny floor.</p></div>`
    },
    'childeharold': {
        id: 'childeharold',
        title: 'Childe Harold\'s Pilgrimage',
        author: 'Lord Byron',
        lat: 53.08,
        lng: -1.19,
        locationName: 'Newstead Abbey, Nottinghamshire',
        locationCoords: '53.08° N, 1.19° W',
        type: 'Inscribed Location',
        typeTag: 'The Romantic Epic',
        accuracy: 'approximate',
        era: '19th Century',
        desc: 'Byron\'s narrative poem capturing the melancholy of a young wanderer, deeply connected to his ancestral home in Nottinghamshire.',
        image: 'https://picsum.photos/seed/childeharold/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">There is a pleasure in the pathless woods,</p><p class="font-body text-lg leading-[1.8]">There is a rapture on the lonely shore,</p><p class="font-body text-lg leading-[1.8]">There is society, where none intrudes,</p><p class="font-body text-lg leading-[1.8]">By the deep Sea, and music in its roar.</p></div>`
    },
    'slough': {
        id: 'slough',
        title: 'Slough',
        author: 'John Betjeman',
        lat: 51.51,
        lng: -0.59,
        locationName: 'Slough, Berkshire',
        locationCoords: '51.51° N, 0.59° W',
        type: 'Inscribed Location',
        typeTag: 'The Modernist Lyric',
        accuracy: 'confirmed',
        era: '20th Century',
        desc: 'A satirical and scathing attack on 20th-century industrialization and the drab reality of the trading estate in Slough.',
        image: 'https://picsum.photos/seed/slough/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">Come friendly bombs and fall on Slough!</p><p class="font-body text-lg leading-[1.8]">It isn't fit for humans now,</p><p class="font-body text-lg leading-[1.8]">There isn't grass to graze a cow.</p><p class="font-body text-lg leading-[1.8]">Swarm over, Death!</p></div>`
    },
    'whitsun': {
        id: 'whitsun',
        title: 'The Whitsun Weddings',
        author: 'Philip Larkin',
        lat: 53.74,
        lng: -0.34,
        locationName: 'Hull Paragon Station, East Riding',
        locationCoords: '53.74° N, 0.34° W',
        type: 'Inscribed Location',
        typeTag: 'The Modernist Lyric',
        accuracy: 'approximate',
        era: '20th Century',
        desc: 'A masterful observation of English life as seen from a train journey south from Hull, passing numerous newlywed couples setting off on their honeymoons.',
        image: 'https://picsum.photos/seed/whitsun/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">That Whitsun, I was late getting away:</p><p class="font-body text-lg leading-[1.8]">Not till about</p><p class="font-body text-lg leading-[1.8]">One-twenty on the sunlit Saturday</p><p class="font-body text-lg leading-[1.8]">Did my three-quarters-empty train pull out, All windows down, all cushions hot, all sense</p><p class="font-body text-lg leading-[1.8]">Of being in a hurry gone.</p></div>`
    },
    'midwinter': {
        id: 'midwinter',
        title: 'In the Bleak Midwinter',
        author: 'Christina Rossetti',
        lat: 51.50,
        lng: -0.12,
        locationName: 'London, England',
        locationCoords: '51.50° N, 0.12° W',
        type: 'Inscribed Location',
        typeTag: 'The Victorian Lyric',
        accuracy: 'compositional',
        era: '19th Century',
        desc: 'A beloved Christmas carol text reflecting on the harshness of winter against the warmth of spiritual devotion.',
        image: 'https://picsum.photos/seed/midwinter/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">In the bleak mid-winter</p><p class="font-body text-lg leading-[1.8]">Frosty wind made moan;</p><p class="font-body text-lg leading-[1.8]">Earth stood hard as iron,</p><p class="font-body text-lg leading-[1.8]">Water like a stone;</p><p class="font-body text-lg leading-[1.8]">Snow had fallen, snow on snow,</p><p class="font-body text-lg leading-[1.8]">Snow on snow,</p><p class="font-body text-lg leading-[1.8]">In the bleak mid-winter</p><p class="font-body text-lg leading-[1.8]">Long ago.</p></div>`
    },
    'nightingale': {
        id: 'nightingale',
        title: 'Ode to a Nightingale',
        author: 'John Keats',
        lat: 51.56,
        lng: -0.16,
        locationName: 'Hampstead Heath, London',
        locationCoords: '51.56° N, 0.16° W',
        type: 'Inscribed Location',
        typeTag: 'The Romantic Lyric',
        accuracy: 'compositional',
        era: '19th Century',
        desc: 'Written under a plum tree in the garden of Wentworth Place, Keats contemplates the immortal beauty of the bird\'s song in contrast to mortal suffering.',
        image: 'https://picsum.photos/seed/nightingale/800/600',
        textHTML: `<div class="space-y-4 max-w-xl"><p class="font-body text-lg leading-[1.8] first-letter:text-5xl first-letter:font-headline first-letter:float-left first-letter:mr-3 first-letter:text-primary">My heart aches, and a drowsy numbness pains</p><p class="font-body text-lg leading-[1.8]">My sense, as though of hemlock I had drunk,</p><p class="font-body text-lg leading-[1.8]">Or emptied some dull opiate to the drains</p><p class="font-body text-lg leading-[1.8]">One minute past, and Lethe-wards had sunk:</p><p class="font-body text-lg leading-[1.8]">'Tis not through envy of thy happy lot,</p><p class="font-body text-lg leading-[1.8]">But being too happy in thine happiness,—</p><p class="font-body text-lg leading-[1.8]">That thou, light-winged Dryad of the trees</p><p class="font-body text-lg leading-[1.8]">In some melodious plot</p><p class="font-body text-lg leading-[1.8]">Of beechen green, and shadows numberless,</p><p class="font-body text-lg leading-[1.8]">Singest of summer in full-throated ease.</p></div>`
    }
};

Object.assign(POETRY_DATA, POETRY_DATA_EXTRA2);
