#!/bin/bash

PORT=8222

echo "Checking if port $PORT is in use..."
PID=$(lsof -ti tcp:$PORT)

if [ ! -z "$PID" ]; then
    echo "Port $PORT is currently in use by PID $PID. Killing the process..."
    kill -9 $PID
    echo "Process killed."
else
    echo "Port $PORT is free."
fi

echo "Starting Node.js server on port $PORT..."
node server.js
